//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BMSS.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class CashSalesDocPays
    {
        public long DocEntry { get; set; }
        public int LineNum { get; set; }
        public string GLCode { get; set; }
        public string GLName { get; set; }
        public string PaymentType { get; set; }
        public decimal PaidAmount { get; set; }
        public string PaymentRemarks { get; set; }
        public string ChequeNoReference { get; set; }
        public string TStamp { get; set; }
        public string PayLocation { get; set; }
    
        public virtual CashSalesDocH CashSalesDocH { get; set; }
    }
}
