//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BMSS.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeliveryPlanner
    {
        public int Idkey { get; set; }
        public Nullable<int> SortSequence { get; set; }
        public int SNo { get; set; }
        public string DocType { get; set; }
        public System.DateTime CreatedDateTime { get; set; }
        public string ReferenceNo { get; set; }
        public Nullable<int> CreatorLocation { get; set; }
        public string AddedBy { get; set; }
        public string DeliveryLocation { get; set; }
        public System.DateTime DeliveryDate { get; set; }
        public string DeliveryTime { get; set; }
        public int Reprint { get; set; }
        public string Remarks { get; set; }
        public string LastPrintedBy { get; set; }
        public string LastDriver { get; set; }
        public string LastVehicleNo { get; set; }
        public string LastStatus { get; set; }
        public string LastTripNo { get; set; }
        public string LastFromLocation { get; set; }
        public string TripsOutOfTotal { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
    }
}
