//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BMSS.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class DODocStockLoan
    {
        public long DocEntry { get; set; }
        public string DocNum { get; set; }
        public long DODocEntry { get; set; }
        public int LineNum { get; set; }
        public string ItemCode { get; set; }
        public string Description { get; set; }
        public decimal Qty { get; set; }
        public bool Reversed { get; set; }
        public string TStamp { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public string ReversedBy { get; set; }
        public Nullable<System.DateTime> ReversedOn { get; set; }
    
        public virtual DODocH DODocH { get; set; }
    }
}
