//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BMSS.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvMovmentView
    {
        public string TransType { get; set; }
        public System.DateTime DocDate { get; set; }
        public string DocNum { get; set; }
        public string SAPDocNum { get; set; }
        public string CardCode { get; set; }
        public string CardName { get; set; }
        public decimal InQty { get; set; }
        public decimal OutQty { get; set; }
        public decimal UnitPrice { get; set; }
        public string ItemCode { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string Location { get; set; }
        public string BASE_REF { get; set; }
    }
}
