//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BMSS.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentDocH
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PaymentDocH()
        {
            this.PaymentDocLs = new HashSet<PaymentDocLs>();
            this.PaymentDocNotes = new HashSet<PaymentDocNotes>();
        }
    
        public long DocEntry { get; set; }
        public string DocNum { get; set; }
        public System.DateTime DocDate { get; set; }
        public string CardCode { get; set; }
        public string CardName { get; set; }
        public string GLCode { get; set; }
        public string GLName { get; set; }
        public string PaymentType { get; set; }
        public decimal PaidAmount { get; set; }
        public decimal TotalDiscountAmount { get; set; }
        public string PaymentRemarks { get; set; }
        public string ChequeNoReference { get; set; }
        public short Status { get; set; }
        public short PrintedStatus { get; set; }
        public bool SubmittedToSAP { get; set; }
        public short SyncStatus { get; set; }
        public bool SyncedToSAP { get; set; }
        public string SAPDocNum { get; set; }
        public string SyncRemarks { get; set; }
        public string Ref { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> PrintedOn { get; set; }
        public string PrintedBy { get; set; }
        public string PaymentLocation { get; set; }
        public string SubmittedBy { get; set; }
        public Nullable<System.DateTime> SubmittedOn { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PaymentDocLs> PaymentDocLs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PaymentDocNotes> PaymentDocNotes { get; set; }
    }
}
