//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BMSS.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentDocLs
    {
        public long DocEntry { get; set; }
        public int LineNum { get; set; }
        public string ReferenceDocNum { get; set; }
        public string ReferenceDocType { get; set; }
        public decimal DiscountAmount { get; set; }
        public decimal PaymentAmount { get; set; }
        public Nullable<System.DateTime> DocDate { get; set; }
        public decimal DocTotal { get; set; }
        public decimal BalanceDue { get; set; }
    
        public virtual PaymentDocH PaymentDocH { get; set; }
    }
}
