//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BMSS.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockBalanceLog
    {
        public long Id { get; set; }
        public string ItemCode { get; set; }
        public decimal DOBalance { get; set; }
        public decimal SLBalance { get; set; }
        public decimal CSBalance { get; set; }
        public decimal CSCBalance { get; set; }
        public decimal GRPOBalance { get; set; }
        public decimal SRBalance { get; set; }
        public decimal SIBalance { get; set; }
        public decimal STBalance { get; set; }
        public string Location { get; set; }
        public System.DateTime UpdatedOn { get; set; }
        public string UpdatedBy { get; set; }
    }
}
