//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BMSS.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockIssueDocLs
    {
        public long DocEntry { get; set; }
        public int LineNum { get; set; }
        public string ItemCode { get; set; }
        public string Description { get; set; }
        public string OverwriteDescription { get; set; }
        public string Description2 { get; set; }
        public string Description3 { get; set; }
        public string Description4 { get; set; }
        public string Description5 { get; set; }
        public string Description6 { get; set; }
        public string Location { get; set; }
        public string LocationText { get; set; }
        public decimal Qty { get; set; }
        public decimal UnitPrice { get; set; }
        public string SerialNumber { get; set; }
    
        public virtual StockIssueDocH StockIssueDocH { get; set; }
    }
}
