//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BMSS.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockTransDocH
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StockTransDocH()
        {
            this.StockTransDocLs = new HashSet<StockTransDocLs>();
            this.StockTransDocNotes = new HashSet<StockTransDocNotes>();
        }
    
        public long DocEntry { get; set; }
        public string DocNum { get; set; }
        public System.DateTime DocDate { get; set; }
        public short Status { get; set; }
        public short PrintedStatus { get; set; }
        public bool SubmittedToSAP { get; set; }
        public short SyncStatus { get; set; }
        public bool SyncedToSAP { get; set; }
        public string SAPDocNum { get; set; }
        public string SyncRemarks { get; set; }
        public string Ref { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<System.DateTime> PrintedOn { get; set; }
        public string PrintedBy { get; set; }
        public Nullable<int> PrintedCount { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StockTransDocLs> StockTransDocLs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StockTransDocNotes> StockTransDocNotes { get; set; }
    }
}
