//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BMSS.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class SyncErrLog
    {
        public long DocEntry { get; set; }
        public string errMSg { get; set; }
        public string InnerException { get; set; }
        public string FileName { get; set; }
        public Nullable<int> LineNumber { get; set; }
        public System.DateTime CreatedOn { get; set; }
    }
}
