//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BMSS.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class SyncLog
    {
        public int DocEntry { get; set; }
        public string DocType { get; set; }
        public string Status { get; set; }
        public string Msg { get; set; }
        public System.DateTime CreatedOn { get; set; }
    }
}
