// <auto-generated />
namespace BMSS.WebUI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class preferredSalesPerson : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(preferredSalesPerson));
        
        string IMigrationMetadata.Id
        {
            get { return "202012010247574_preferred-Sales Person"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
