Namespace Models
	Public Class DODocH
        Public Property DocEntry() As String
        Public Property DocNum() As String
        Public Property DocDate() As String
        Public Property DueDate() As String
        Public Property DeliveryDate() As String
        Public Property DeliveryTime() As String
        Public Property Status() As String
        Public Property PrintedStatus() As String
        Public Property CopiedSQ() As String
        Public Property CardCode() As String
        Public Property CardName() As String
        Public Property PaymentTerm() As String
        Public Property PaymentTermName() As String
        Public Property Currency() As String
        Public Property CustomerRef() As String
        Public Property CustomerTelNo() As String
        Public Property OfficeTelNo() As String
        Public Property Fax() As String
        Public Property SlpCode() As String
        Public Property SlpName() As String
        Public Property HeaderRemarks1() As String
        Public Property HeaderRemarks2() As String
        Public Property HeaderRemarks3() As String
        Public Property HeaderRemarks4() As String
        Public Property FooterRemarks1() As String
        Public Property FooterRemarks2() As String
        Public Property FooterRemarks3() As String
        Public Property FooterRemarks4() As String
        Public Property ShipTo() As String
        Public Property ShipToAddress1() As String
        Public Property ShipToAddress2() As String
        Public Property ShipToAddress3() As String
        Public Property ShipToAddress4() As String
        Public Property ShipToAddress5() As String
        Public Property BillTo() As String
        Public Property BillToAddress1() As String
        Public Property BillToAddress2() As String
        Public Property BillToAddress3() As String
        Public Property BillToAddress4() As String
        Public Property BillToAddress5() As String
        Public Property SelfCollect() As String
        Public Property SelfCollectRemarks1() As String
        Public Property SelfCollectRemarks2() As String
        Public Property SelfCollectRemarks3() As String
        Public Property SelfCollectRemarks4() As String
        Public Property SelfCollectRemarks5() As String
        Public Property DiscByPercent() As String
        Public Property DiscPercent() As String
        Public Property DiscAmount() As String
        Public Property NetTotal() As String
        Public Property GstTotal() As String
        Public Property GrandTotal() As String
        Public Property Rounding() As String
        Public Property GrandTotalAftRounding() As String
        Public Property TotalWeight() As String
        Public Property BalanceDue() As String
        Public Property SubmittedToSAP() As String
        Public Property SAPDocNum() As String
        Public Property HaveStockLoan() As String
        Public Property CreatedOn() As String
        Public Property CreatedBy() As String
        Public Property UpdatedBy() As String
        Public Property UpdatedOn() As String
    End Class
End Namespace
